### ISSUE TITLE
Can not select text in any of the panes

### ISSUE THREAD

**Issue by benalb** [samtay/so#10]
Can not select text, to copy and paste, in any of the panes.

Steps to reproduce the behavior
Do any search, try to select text in any of the panes with the mouse. Nothing happens, the text is not selected, nor copied to clipboard.

 - OS: Void LInux x86_64
 - Terminal: urxvt, alacritty, with and without tmux.
 - `so --version`:  so 0.4.2

**Comment by samtay** [comment]
I agree, this would be a nice feature, but currently isn't possible with the `cursive` library that I'm using. See [here](https://github.com/gyscos/cursive/issues/477#issuecomment-663917718) for an explanation and a few suggestions.

If I can get around to either #7 or #9 perhaps this issue would be alleviated, and make the tool more useful.

**Comment by benalb** [comment]
> See [here](https://github.com/gyscos/cursive/issues/477#issuecomment-663917718) for an explanation and a few suggestions.

In tmux, entering copy-mode and selecting text, and then paste it in another pane, with the default key-bindings, works, so I will close the issue. Thank you very much, so is really awesome.

**Comment by samtay** [comment]
I just added a `y` shortcut to pipe contents to the system clipboard. See [here](https://github.com/samtay/so/tree/1484f6763b9a7dd782a002764886c053477f2181#system-clipboard-integration) for how to set it up.
