### ISSUE TITLE
Doesn't work in Git Bash on Windows

### ISSUE THREAD

**Issue by laralex** [samtay/so#4]
**Describe the bug**
Trying to run `so whatever` in Git Bash on Windows having prebuilt binary of `so` for x86_64 results with a message:
Getting mode failed
✖ Crossterm error: IO-error occurred

**To Reproduce**
1. download so-v0.3.6-x86_64-pc-windows-msvc.zip and unzip it
2. run Git Bash (can be obtained by installing Git on Windows and selecting a checkbox in installer)
3. run "so help me out" in it

**Environment**
 - OS: Windows 10 Education
 - Terminal: Git Bash
 - `so --version`: 0.3.6

**Additional context**
Works fine in PowerShell and CMD, the bug doesn't disappear even with `--no-lucky`

**Comment by samtay** [comment]
Hey @laralex thanks for the issue. I hopped onto the [`crossterm` discord](https://discord.gg/K4nyTDB) to ask about this, and apparently Git Bash is not fully supported, particularly around user input (which is obviously a big part of `so` and `cursive`). Anyone who wants to investigate this further can pop into that chat and try to gather some info, but I consider it out of scope of `so`, so I'm going to close this. Sorry for the inconvenience anyhow.
