### ISSUE TITLE
All requests return "Reqwest error: error decoding response body: expected value at line 1 column 1"

### ISSUE THREAD

**Issue by lavedon** [samtay/so#46]
**Describe the bug**
Any use of the tool will return the error message "Reqwest error: error decoding response body: expected value at line 1 column 1"
I have tried this on two machines now.

**To Reproduce**
1. Use the CLI tool with any search term.
2. Observe error. 

**Screenshots**
![image](https://github.com/user-attachments/assets/dc15c1d5-0a0b-4155-aebe-4153b643c6a7)

**Environment**
Windows Powershell (tried on both Windows 10 and Windows 11).

**Additional context**
Thank you!!!!!

**Comment by chameleon-lizard** [comment]
Same stuff, Ubuntu 23.10, fish shell, installed from source like 15 minutes ago.

**Comment by samtay** [comment]
Should be working now. Can you run `cargo install --locked --git https://github.com/samtay/so.git --tag v0.4.10` and let me know if it persists? Also post the output of `cat ~/.config/so/config.yml`

**Comment by chameleon-lizard** [comment]
Yeah, it runs great now! Thank you!

**Comment by kqvanity** [comment]
@samtay
Can you update the cartes-io registry with the latest version?

**Comment by samtay** [comment]
> @samtay Can you update the cartes-io registry with the latest version?

[Done!](https://crates.io/crates/so/0.4.10)
