### ISSUE TITLE
feature: highlight url links and open it in browser

### ISSUE THREAD

**Issue by D1mon** [samtay/so#7]
and open link (url) `questions tab` in browser (`xdg-open` app)

**Comment by samtay** [comment]
Yeah this is a cool idea. I think the [open](https://docs.rs/open/1.4.0/open/) crate would make this pretty easy. Probably add a keybinding to the <kbd>o</kbd> key, and if opening fails, default to a cursive pop-up dialog with the URL.

**Comment by samtay** [comment]
As of [v0.4.8](https://github.com/samtay/so/releases/tag/v0.4.8) pressing `o` will open the focused question & answer in the browser.
